import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {measuredSeconds} from '../activity.js';
const now=Date.now(),previous={last_heartbeat_at:new Date(now-30000).toISOString(),was_active:true};
assert.equal(measuredSeconds(previous,true,now),30);
assert.equal(measuredSeconds(previous,false,now),0);
assert.equal(measuredSeconds({...previous,was_active:false},true,now),0);
assert.equal(measuredSeconds({...previous,last_heartbeat_at:new Date(now-180000).toISOString()},true,now),0);
assert.equal(measuredSeconds({...previous,last_heartbeat_at:null},true,now),0);
assert.equal(measuredSeconds({...previous,last_heartbeat_at:new Date(now+1000).toISOString()},true,now),0);
console.log('PASS Active time excludes idle, first observations, clock reversal and disconnected gaps');
const base='http://127.0.0.1:3548';
const server=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'3548',NODE_ENV:'test',SESSION_DAYS:'7',SESSION_REFRESH_DAYS:'3',DATABASE_URL:'',PGLITE_DIR:'',OWNER_EMAIL:'activity-owner@example.org',APP_BASE_URL:base,SMTP_HOST:'',SMTP_USER:'',SMTP_PASS:'',LODGE_ACCESS_CODE:'',DDGM_EMAIL:'unused@example.org'},stdio:'ignore'});
let passed=0;const check=(name,ok)=>{assert.ok(ok,name);passed++;console.log('PASS '+name)};
async function api(path,token,method='GET',body,client='web'){const form=body instanceof FormData;const r=await fetch(base+path,{method,headers:{...(token?{Authorization:`Bearer ${token}`}:{ }),...(body&&!form?{'Content-Type':'application/json'}:{}),'X-Stone-Square-Client':client},body:body?(form?body:JSON.stringify(body)):undefined});return{status:r.status,data:r.headers.get('content-type')?.includes('json')?await r.json():await r.text()};}
try{
 for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,100));}
 const password='Local activity test password';const owner=(await api('/api/auth/register',null,'POST',{email:'activity-owner@example.org',name:'WM QA Owner',password})).data;
 async function officer(role){const email=role+'@example.org';const invite=(await api('/api/officers/invite',owner.token,'POST',{email,name:'QA '+role,role})).data;return(await api('/api/auth/register',null,'POST',{email,name:'QA '+role,password,invitationToken:new URL(invite.inviteUrl).searchParams.get('invite')})).data;}
 const treasurer=await officer('treasurer'),basic=await officer('viewer');
 check('Registration reports the actual 90-day session expiration', owner.session.lifetimeDays === 90 && Math.abs(Date.parse(owner.session.expiresAt) - Date.now() - 90*86400000) < 10000);
 const restored = (await api('/api/auth/me', owner.token)).data;
 check('Remembered sign-in returns the same policy and expiration', restored.session.lifetimeDays === 90 && restored.session.expiresAt === owner.session.expiresAt);
 check('Anonymous cannot read officer activity',(await api('/api/admin/activity')).status===401);
 check('Treasurer cannot read other officers activity',(await api('/api/admin/activity',treasurer.token)).status===403);
 check('Basic account cannot read dashboard activity',(await api('/api/admin/activity',basic.token)).status===403);
 for(const path of ['/api/documents','/api/minutes','/api/treasury','/api/approvals','/api/officers','/api/submission-profiles','/api/proposals'])check('WM can open '+path,(await api(path,owner.token)).status===200);
 const dues=await api('/api/dues',owner.token);check('WM passes the dues access gate with missing test connection',dues.status===503&&dues.data.configured===false);
 check('WM can prepare proposals',(await api('/api/proposals',owner.token,'POST',{})).status===400);
 await api('/api/activity/heartbeat',treasurer.token,'POST',{active:true,area:'treasury',activeSeconds:999999},'mac');
 await new Promise(r=>setTimeout(r,1100));await api('/api/activity/heartbeat',treasurer.token,'POST',{active:true,area:'treasury'},'mac');
 let activity=(await api('/api/admin/activity?userId='+treasurer.user.id,owner.token)).data;
 check('WM sees sign-in and Mac client',activity.sessions.length===1&&activity.sessions[0].startedAt&&activity.sessions[0].client==='Mac app');
 check('Server measures time instead of trusting supplied totals',activity.sessions[0].activeSeconds>=1&&activity.sessions[0].activeSeconds<10);
 check('User filter limits sessions and actions',activity.sessions.every(s=>s.userId===treasurer.user.id)&&activity.events.every(e=>e.userId===treasurer.user.id));
 check('Work area appears in history',activity.events.some(e=>e.action==='workspace_opened'&&e.detail==='Treasurer Reports'));
 check('Measured time is attributed to the active work area',activity.sessions[0].areas.some(area=>area.area==='Treasurer Reports'&&area.seconds>=1));
 check('A safe click can be recorded without form content',(await api('/api/activity/interaction',treasurer.token,'POST',{kind:'activate',area:'treasury',target:'View finalized report'})).status===200);
 activity=(await api('/api/admin/activity?userId='+treasurer.user.id,owner.token)).data;
 check('WM sees a named dashboard interaction',activity.events.some(e=>e.action==='dashboard_interaction'&&e.detail.includes('Clicked Treasurer Reports')&&e.detail.includes('View finalized report')));
 check('Invalid interaction areas are rejected',(await api('/api/activity/interaction',treasurer.token,'POST',{kind:'activate',area:'passwords',target:'Secret'})).status===400);
 const incidentReference='SS22-A1B2C3D4';
 check('Officer can record a safe dashboard incident',(await api('/api/activity/incidents',treasurer.token,'POST',{reference:incidentReference,area:'minutes',path:'/api/minutes/123e4567-e89b-12d3-a456-426614174000?private=never-store-this',method:'GET',status:503,category:'service_response',state:'open',sourceText:'private transcript must be ignored'})).status===201);
 let incidentActivity=(await api('/api/admin/activity?userId='+treasurer.user.id,owner.token)).data;
 const openIncident=incidentActivity.incidents.find(item=>item.reference===incidentReference);
 check('WM error log identifies the user, area and safe route',openIncident?.actor==='QA treasurer'&&openIncident.area==='Meeting Minutes'&&openIncident.path==='/api/minutes/:record'&&openIncident.state==='open');
 check('Error log excludes query strings and submitted record content',!JSON.stringify(incidentActivity).includes('never-store-this')&&!JSON.stringify(incidentActivity).includes('private transcript'));
 await api('/api/activity/incidents',treasurer.token,'POST',{reference:incidentReference,area:'minutes',path:'/api/minutes/123e4567-e89b-12d3-a456-426614174000',method:'GET',status:200,category:'temporary_connection',state:'recovered'});
 incidentActivity=(await api('/api/admin/activity?userId='+treasurer.user.id,owner.token)).data;
 check('Recovered incidents close instead of creating a duplicate',incidentActivity.incidents.filter(item=>item.reference===incidentReference).length===1&&incidentActivity.incidents.find(item=>item.reference===incidentReference).state==='recovered'&&Boolean(incidentActivity.incidents.find(item=>item.reference===incidentReference).recoveredAt));
 const banking=new FormData();banking.set('intent','save');banking.set('sourceText','Period: August 2026\nChecking\nBeginning balance: $100.00\nEnding balance: $100.00\nNo receipts or payments.');
 const created=await api('/api/treasury/generate',treasurer.token,'POST',banking);check('Report activity fixture saves',created.status===201);
 const named=(await api('/api/admin/activity?userId='+treasurer.user.id,owner.token)).data;
 const expectedPeriod=new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${created.data.report.draft.periodEnd}T12:00:00Z`));
 check('Actions identify the report in readable language',named.events.some(e=>e.action==='treasury_created'&&e.detail.includes('Treasurer report')&&e.detail.includes(expectedPeriod)));
 check('Session response excludes credentials and raw financial details',!JSON.stringify(activity).includes(treasurer.token)&&!JSON.stringify(activity).includes('auth_hash')&&!JSON.stringify(activity).includes('details_json'));
 const elapsed=activity.sessions[0].activeSeconds;
 await api('/api/activity/heartbeat',treasurer.token,'POST',{active:false,area:'treasury'},'mac');await new Promise(r=>setTimeout(r,1100));await api('/api/activity/heartbeat',treasurer.token,'POST',{active:false,area:'treasury'},'mac');
 activity=(await api('/api/admin/activity?userId='+treasurer.user.id,owner.token)).data;
 check('Idle polling adds no active time',activity.sessions[0].activeSeconds===elapsed&&activity.sessions[0].status==='Idle');
 await api('/api/auth/logout',treasurer.token,'POST',{});
 activity=(await api('/api/admin/activity?userId='+treasurer.user.id,owner.token)).data;
 check('Sign-out closes history while preserving duration',activity.sessions[0].status==='Ended'&&activity.sessions[0].endedAt&&activity.sessions[0].activeSeconds===elapsed&&activity.events.some(e=>e.action==='signed_out'));
 check('Signed-out credential no longer works',(await api('/api/activity/heartbeat',treasurer.token,'POST',{active:true})).status===401);
 check('WM administrator cannot be demoted',(await api('/api/admin/accounts/'+owner.user.id+'/role',owner.token,'PUT',{role:'member'})).status===403);
 check('Basic account cannot change account roles',(await api('/api/admin/accounts/'+basic.user.id+'/role',basic.token,'PUT',{role:'treasurer'})).status===403);
 check('WM can assign report preparation access',(await api('/api/admin/accounts/'+basic.user.id+'/role',owner.token,'PUT',{role:'assistant_treasurer'})).status===200);
 check('Role change ends old sign-ins',(await api('/api/auth/me',basic.token)).status===401);
 const updated=(await api('/api/auth/login',null,'POST',{email:'viewer@example.org',password},'mac')).data;
 check('Password sign-in reports a fresh 90-day session', updated.session.lifetimeDays === 90 && Math.abs(Date.parse(updated.session.expiresAt) - Date.now() - 90*86400000) < 10000);
 check('Changed role is effective on next sign-in',updated.user.role==='assistant_treasurer'&&updated.user.treasuryAccess==='prepare');
 activity=(await api('/api/admin/activity',owner.token)).data;
 check('Role change is retained in action history',activity.events.some(e=>e.action==='officer_role_changed'&&e.detail.includes('assistant treasurer')));
 check('Activity filter rejects neither empty nor invalid day values',(await api('/api/admin/activity?days=invalid',owner.token)).status===200);
 console.log(`${passed} officer activity and WM access checks passed.`);
}finally{server.kill();}
