import assert from 'node:assert/strict';
import {organizeReport,REPORT_GENERATOR_RULES} from '../report-ai.js';
const schema={types:{event:{name:'Event Proposal',fields:[{id:'title',label:'Event name',kind:'text',req:true},{id:'budget',label:'Budget',kind:'budget'},{id:'price',label:'Price',kind:'money'},{id:'approved',label:'Approved funds',kind:'money'},{id:'time',label:'Time',kind:'time'},{id:'date',label:'Date',kind:'date'},{id:'notes',label:'Notes',kind:'long'}]}},masterTypes:{}};
const input={source:'Community dinner on October 1, 2026. Plates cost $20.00. Food, 300, Stone Square. No vote was taken.',type:'event',master:false,fields:{notes:'Existing note must remain.'}};
const suggestion={suggestions:[{field:'title',value:'Community dinner',quote:'Community dinner'},{field:'price',value:'20.00',quote:'Plates cost $20.00.'},{field:'date',value:'2026-10-01',quote:'October 1, 2026'},{field:'budget',value:'Food, 300, Stone Square',quote:'Food, 300, Stone Square.'}],warnings:['No vote was taken.']};
let calls=0;
const run=(value=suggestion,data=input)=>organizeReport(data,{schema,generateStructured:async request=>{calls++;assert.equal(request.purpose,'report');assert.equal(request.instructions,REPORT_GENERATOR_RULES);assert.match(request.input,/Existing note must remain/);return structuredClone(value);}});
const result=await run();assert.equal(result.fields.price,'20.00');assert.equal(result.fields.date,'2026-10-01');assert.equal(result.fields.notes,undefined);assert.equal(input.fields.notes,'Existing note must remain.');
for(const bad of [{field:'signatureName',value:'Signed',quote:'Community dinner'},{field:'price',value:'999',quote:'Plates cost $20.00.'},{field:'date',value:'2026-10-02',quote:'October 1, 2026'},{field:'title',value:'Invented',quote:'Not in the source'}])await assert.rejects(run({suggestions:[bad],warnings:[]}));
await assert.rejects(run({...suggestion,suggestions:[suggestion.suggestions[0],suggestion.suggestions[0]]}));
const before=calls;await assert.rejects(run(suggestion,{...input,source:''}));await assert.rejects(run(suggestion,{...input,fields:{signatureName:'x'}}));assert.equal(calls,before);
await assert.rejects(organizeReport(input,{schema}),e=>e.statusCode===503);
await assert.rejects(run({suggestions:[{field:'budget',value:'Food, 9000, Jephthah',quote:'Food, 300, Stone Square.'}],warnings:[]}),/budget changed/);
await assert.rejects(run({suggestions:[{field:'approved',value:'500',quote:'The request for $500 was denied. No money was approved.'}],warnings:[]},{...input,source:'The request for $500 was denied. No money was approved.'}),/approved funds/);
await assert.rejects(run({suggestions:[{field:'time',value:'21:00',quote:'Dinner starts at 6:00 PM.'}],warnings:[]},{...input,source:'Dinner starts at 6:00 PM.'}),/time does not match/);
const timed=await run({suggestions:[{field:'time',value:'18:00',quote:'Dinner starts at 6:00 PM.'}],warnings:[]},{...input,source:'Dinner starts at 6:00 PM.'});assert.equal(timed.fields.time,'18:00');
await assert.rejects(run({suggestions:[{field:'budget',value:'Food, 300',quote:'Food, 300, Stone Square.'}],warnings:[]}),/budget changed/);
const approved=await run({suggestions:[{field:'approved',value:'500',quote:'The Lodge approved the $500 request.'}],warnings:[]},{...input,source:'The Lodge approved the $500 request.'});assert.equal(approved.fields.approved,'500');
await assert.rejects(run({suggestions:[{field:'budget',value:'Food, 300',quote:'Food, 300'}],warnings:[]}),/omitted part of a row/);
console.log('Report field organization, evidence, amounts, dates, identity boundaries and input retention passed without paid calls.');
